# Generated by Django 3.1.7 on 2021-05-15 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='equipo',
            table='equipos',
        ),
        migrations.AlterModelTable(
            name='jugador',
            table='jugadores',
        ),
        migrations.AlterModelTable(
            name='nivel',
            table='niveles',
        ),
    ]
