# Generated by Django 3.1.7 on 2021-05-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores_app', '0002_auto_20210515_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='apellido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
